### ISSUE TITLE
OpenSSL 1.1

### ISSUE THREAD

**Issue by ghost** [cygwinports/mingw64-x86_64-openssl#1]
Current version is 1.0.2o:

https://github.com/cygwinports/mingw64-x86_64-openssl/blob/089e763ad624ebcaf8a3521105454cd386557d9b/mingw64-x86_64-openssl.cygport#L4-L5

However OpenSSL 1.1 has been available for several years now:

https://github.com/openssl/openssl/releases/tag/OpenSSL_1_1_0

and certain libraries require OpenSSL 1.1:

https://github.com/curl/curl-for-win

## workaround

its available here:

https://curl.haxx.se/windows

**Comment by cup** [comment]
https://github.com/cygwinports/openssl/issues/1

**Comment by yselkowitz** [comment]
This is not a place to request version bumps.  The version will be updated when I have the time to do so in a way that doesn't break other things.
